### ISSUE TITLE
curriculum edit for Pilot MobileBridge Android workshop

### ISSUE THREAD

**Issue by kmolo** [mobilebridge/androidbridge#1]
Starting the Issue for discussion of how to edit the MobileBridge Android curriculum prior to the pilot workshop.

Curriculum:  https://github.com/mobilebridge/androidbridge/wiki
Workshop Issue:  https://github.com/mobilebridge/organizing/issues/7
Post-mortems from MobileBridge iOS workshops:  http://tinyurl.com/MB-iOS-debriefs

High-level goals:
  - [docs.railsbridge.org](http://docs.railsbridge.org) as one model curriculum
  - complementary relationship between [mobilebridge/androidbridge](https://github.com/mobilebridge/androidbridge/wiki) & [codepath/android_guides](https://github.com/codepath/android_guides/)

  
/cc @kgleong @martasmith @nesquena @paulinar

**Comment by kmolo** [comment]
__TL;DR__: let's keep using the wiki format & not move to markdown files for a while
___
One thing the MobileBridge iOS curriculum developers have begun doing is migrating their curriculum from a GitHub wiki to .md markdown files, to make it easier for contributors to fork the curriculum, make edits, and submit Pull Requests.  

[Bonus points because GitHub notifies you about PRs, but doesn't notify you when your wiki has been edited (though you can the revision history).]

The downside to this effort so far (in my opinion) has been that the curriculum is now sprawling across many separate repos:

> iosbridge is now superseded by [iosbridge-rottentomatoes](https://github.com/mobilebridge/iosbridge-rottentomatoes) and [iosbridge-prototyping](https://github.com/mobilebridge/iosbridge-prototyping) but it's hard to see that since the mobilebridge account also contains additional app exercises that they're trying out like [ios-example-tabber](https://github.com/mobilebridge/ios-example-tabber) & [ios-example-tipcalculator-EatOut](https://github.com/mobilebridge/ios-example-tipcalculator-EatOut), plus an older curriculum [iosbridge-tipster-swift](https://github.com/mobilebridge/iosbridge-tipster-swift)

> it is possible that after a period of experimentation, it will be possible to combine the stable curricula into subdirectories in the iosbridge repo. And that this will be a process of experimentation & adoption.  [I've also seen a lot of the experimentation happen in the curriculum developers GitHub accounts, and then the stable curriculum newly created in the MobileBridge GitHub account.]

Something to work out in the future.

**Comment by kmolo** [comment]
I think for the first workshop we can probably keep everything in this mobilebridge/androidbridge repo, but just wanted to point out this issue in the mobilebridge/iosbridge repo:

https://github.com/mobilebridge/iosbridge/issues/9  -- clear MB repo naming format & abstract particular curriculum out of mobilebridge/iosbridge, instead providing links to curriculum choices instead

...so, as multiple Android curricula start evolving, we keep things easy to follow for remote mobilebridge organizers.

**Comment by kmolo** [comment]
Workshop is posted on BridgeTroll:

https://www.bridgetroll.org/events/177

...teacher training is Sat 8/1.

Can we meet before hand to adjust Android 1-Day Workshop for beginners?

/cc @kgleong @martasmith @nesquena @paulinar

**Comment by kgleong** [comment]
@kmolo i can meet 7/28 - 7/31 anytime after 630pm.

**Comment by nidhi1608** [comment]
I can't do 7/28, but 7/29 - 7/31 after 6:30 is fine with me as well.

**Comment by paulinar** [comment]
My availabilities:

7/27 - 7pm onwards

7/28 - 7pm onwards

7/30 - 7pm onwards

7/31 - 7pm onwards

On Mon, Jul 20, 2015 at 10:47 AM, Nidhi Shah <notifications@github.com>
wrote:

> I can't do 7/28, but 7/29 - 7/31 after 6:30 is fine with me as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mobilebridge/androidbridge/issues/1#issuecomment-122965646>
> .
>



-- 
Paulina Ramos

**Comment by kmolo** [comment]
I'm available any of these times, just waiting for @nesquena to chime in.

So far, looks like 7/30 at 7pm works best.  @nesquena does next Thu evening work in your schedule?

**Comment by kmolo** [comment]
Just talked to @nesquena -- he's available on Thu 7/30, so that's our day.

The SC Studios space is no longer available, so we have to find a place to meet.

Would we be able to meet at anyone's office?

**Comment by paulinar** [comment]
We can meet at Uber's second office. :) It's on *685 Market Street* *(near
Montgomery BART station)*. I have to pre-register you all as guests ahead
of time, and so far the list is:

- Nidhi
- Katherine
- Kevin
- Nathan

Am I missing anyone?

On Mon, Jul 20, 2015 at 7:28 PM, kmolo <notifications@github.com> wrote:

> Just talked to @nesquena <https://github.com/nesquena> -- he's available
> on Thu 7/30, so that's our day.
>
> The SC Studios space is no longer available, so we have to find a place to
> meet.
>
> Would we be able to meet at anyone's office?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mobilebridge/androidbridge/issues/1#issuecomment-123131511>
> .
>



-- 
Paulina Ramos

**Comment by tensory** [comment]
I think I'm teaching the October one, not the August event. I'd be up for coming by on 7/30 if it will be useful. Let me know?

**Comment by sporarepo** [comment]
Hi everyone, I will be available to meet on the 30th to help prep for the kick off workshop.

**Comment by Wapples** [comment]
Hi everyone! I am available to attend the prep meeting on the 30th for the workshop on the 1st. I am free to help instruct that workshop as well so let me know how I can help.

**Comment by kmolo** [comment]
@tensory I think it would be useful for you to be involved in the conversation about how to shape the curriculum for MobileBridge workshops distinct from the Learning [Android | iOS] Development style.

@Wapples great news!  Definitely RSVP on https://www.bridgetroll.org/events/177

**Comment by tensory** [comment]
Cool, then I will come by to Uber on 7/30. Thanks, @kmolo!

**Comment by sonamsharma** [comment]
@kmolo I am also available to volunteer for the pilot session and would like to attend the prep meeting 7/30 at Uber office and also the 8/1 and installfest and workshop. Let me know how can I help. 

@paulinar Could you please add my name to the guest list of 7/30 ?

**Comment by kmolo** [comment]
@paulinar any recommendations on delivery around Uber office?

Looking on Yelp I find:

http://www.yelp.com/biz/lers-ros-thai-san-francisco
http://www.yelp.com/biz/house-of-thai-san-francisco-2
http://www.yelp.com/biz/north-india-restaurant-san-francisco
http://www.yelp.com/biz/palmyra-san-francisco

Anyone have any preference for cuisine or restaurant?  Let's pick a restaurant & then we can get into dietary restrictions/preferences (vegetarian, vegan, gluten-free, non-dairy, allergies, etc).

**Comment by tensory** [comment]
Lers Ros is awesome!

**Comment by mdcramer** [comment]
Always having a vegetarian option is nice.

**Comment by sonamsharma** [comment]
North India restaurant has lot of vegetarian and non veg options.

**Comment by kmolo** [comment]
Planning to get food from North India for the workshop, so how about Lers Ros for our working session (this is totally up for debate...happy to do North India twice)?

If Lers Ros, then how about ordering two of the catering menus:

http://lersros.com/menus/larkin-menu/#tab-4ed25123-84b9-5

...the Vegetarian Regular catering menu ( D ) and then one of the other menus ( A or B or C )?

**Comment by paulinar** [comment]
- I don't have any particular food recommendations, *Uber serves free
   dinner at 8:15pm if people can wait that long*. :)
   - I pre-registered the following people, so you should have all gotten
   email invites (let me know if I'm missing anyone)
      - Nidhi
      - Katherine
      - Kevin
      - Nathan
      - Warren
      - Ari
      - Sonam
   - @sporarepo @mdcramer - What are your email addresses? (so I can add
   you both to the pre-registered guest list)

I'll be meeting everyone at the lobby, but feel free to call me at (510)
331-6683 if you get lost!

On Sat, Jul 25, 2015 at 3:33 PM, kmolo <notifications@github.com> wrote:

> Planning to get food from North India for the workshop, so how about Lers
> Ros for our working session (this is totally up for debate...happy to do
> North India twice)?
>
> If Lers Ros, then how about ordering two of the catering menus:
>
> http://lersros.com/menus/larkin-menu/#tab-4ed25123-84b9-5
>
> ...the Vegetarian Regular catering menu ( D ) and then one of the other
> menus ( A or B or C )?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mobilebridge/androidbridge/issues/1#issuecomment-124907438>
> .
>



-- 
Paulina Ramos

**Comment by kmolo** [comment]
I'd be happy bringing snacks instead if folks would be game for Uber dinner?  

(Don't want to assume we can drink/snack from Uber supplies ...but, if we could @paulinar , I'd be happy to save the money for later MobileBridge meetings.)

**Comment by paulinar** [comment]
There will be plenty of drinks and snacks at Uber for you all to indulge in
before dinner starts. :) You don't need to bring anything.

On Sat, Jul 25, 2015 at 10:42 PM, kmolo <notifications@github.com> wrote:

> I'd be happy bringing snacks instead if folks would be game for Uber
> dinner?
>
> (Don't want to assume we can drink/snack from Uber supplies ...but, if we
> could @paulinar <https://github.com/paulinar> , I'd be happy to save the
> money for later MobileBridge meetings.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mobilebridge/androidbridge/issues/1#issuecomment-124947310>
> .
>



-- 
Paulina Ramos

**Comment by kmolo** [comment]
yay!

**Comment by Wapples** [comment]
Did we settle on a time of arrival at Uber tonight?

**Comment by kmolo** [comment]
Yep, 7pm.

**Comment by kmolo** [comment]
@paulinar is meeting everyone in the lobby, so please try to arrive slightly before 7pm, so she doesn't have to ferry individuals up.

call/text her at (510)331-6683 if you're running late.
